# Generated by Django 6.0.6 on 2026-06-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=150, verbose_name='Modelo')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('km', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('combustivel', models.CharField(blank=True, max_length=50, verbose_name='Combustível')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Imagem')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da venda')),
                ('data_venda', models.DateField(auto_now_add=True, verbose_name='Data da venda')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='carros.carro', verbose_name='Carro')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
