# Generated by Django 6.0.6 on 2026-06-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_modelo', models.CharField(blank=True, max_length=150, verbose_name='Modelo do carro')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado')], default='novo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='carros.carro', verbose_name='Carro')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
            },
        ),
    ]
