# Generated by Django 6.0.6 on 2026-06-24 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
        migrations.RenameField(
            model_name='carro',
            old_name='created_at',
            new_name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='combustivel',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='carro_modelo',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='created_at',
        ),
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(default='SEM-PLACA', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='data_lead',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='origem',
            field=models.CharField(default='Site', max_length=100),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='km',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lead',
            name='carro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='carros.carro'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='venda',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='carros.carro'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='CarroImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='carros/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='carros.carro')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
