# Generated by Django 6.0.6 on 2026-06-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_alter_carro_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='carroimagem',
            options={'ordering': ['ordem'], 'verbose_name': 'Imagem do Carro', 'verbose_name_plural': 'Imagens dos Carros'},
        ),
        migrations.AddField(
            model_name='carro',
            name='combustivel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Combustível'),
        ),
        migrations.AddField(
            model_name='carro',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='carro',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='km',
            field=models.PositiveIntegerField(verbose_name='Quilometragem'),
        ),
    ]
