# Generated by Django 6.0.6 on 2026-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_alter_carro_options_alter_carroimagem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
